name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  ci:
    name: Prepare • Test • Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Prepare
        run: |
          python -V
          uv --version
          # Instala o projeto com deps de dev
          uv pip install -e .
          uv pip install .[dev]

      - name: Lint (ruff) and Format Check (black)
        run: |
          uv run -q ruff check .
          uv run -q black --check .

      - name: Test
        env:
          PYTHONWARNINGS: default
        run: |
          uv run -q pytest -q --cov=core --cov-report=term-missing

      - name: Security (pip-audit)
        run: |
          # Auditoria rápida de vulnerabilidades das dependências do ambiente
          uvx --from pip-audit pip-audit --progress-spinner off || true

      - name: Build (sdist + wheel)
        run: |
          uvx --from build build -s -w
